# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    
before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv/
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip uninstall -y pytest-qt
#  - apt-get install xvfb

test:
  stage: test
  script:
    - python -m pytest tests/mut/backend -v
  
coverage:
  stage: test
  script:
    - python -m pytest tests/mut/backend/ --cov minegauler/backend --cov-report term --cov-report html:coverage/backend
  artifacts:
    paths:
    - coverage
    expire_in: 1 day
  only:
    - v4/dev

pages:
  stage: deploy
  before_script: []
  script:
    - mkdir public/
    - mv coverage/ public/
  dependencies:
    - coverage
  artifacts:
    paths:
      - public
  only:
    - v4/dev